server:
  port: 8080
  error:
    path: /error
spring:
  # mongo
  data:
    mongodb:
      uri: mongodb://appboot:baiduyun@106.12.103.25:27017/appboot
      connections-per-host: 20
      min-connections-per-host: 20
      option:
        threads-allowed-to-block-for-connection-multiplier: 10
        socket-timeout: 0
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        heartbeat-frequency: 10000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 
    timeout: 5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
#  profiles:
#    active: 